using System;
using System.Collections.Generic;
using System.Text;

namespace eGym.Core.Domain.Context.SeedData
{
    internal static class CountrySeedData
    {
        public static Country[] Data = new Country[]
        {
            new Country() { Country_ID = 1, Country_IsoCode = "004", Country_CountryName = "Afganistan", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 2, Country_IsoCode = "008", Country_CountryName = "Albania", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 3, Country_IsoCode = "012", Country_CountryName = "Algeria", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 4, Country_IsoCode = "020", Country_CountryName = "Andorra", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 5, Country_IsoCode = "024", Country_CountryName = "Angola", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 6, Country_IsoCode = "660", Country_CountryName = "Anguilla", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 7, Country_IsoCode = "028", Country_CountryName = "Antigua e Barbuda", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 8, Country_IsoCode = "530", Country_CountryName = "Antille Olandesi", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 9, Country_IsoCode = "682", Country_CountryName = "Arabia Saudita", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 10, Country_IsoCode = "032", Country_CountryName = "Argentina", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 11, Country_IsoCode = "051", Country_CountryName = "Armenia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 12, Country_IsoCode = "533", Country_CountryName = "Aruba", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 13, Country_IsoCode = "654", Country_CountryName = "Ascension", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 14, Country_IsoCode = "036", Country_CountryName = "Australia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 15, Country_IsoCode = "040", Country_CountryName = "Austria", Country_Language = "ENG", Country_VIESCode = "AT", Country_CFiscCode = null },
            new Country() { Country_ID = 16, Country_IsoCode = "031", Country_CountryName = "Azerbaigian", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 17, Country_IsoCode = "044", Country_CountryName = "Bahamas", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 18, Country_IsoCode = "048", Country_CountryName = "Bahrein", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 19, Country_IsoCode = "050", Country_CountryName = "Bangladesh", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 20, Country_IsoCode = "052", Country_CountryName = "Barbados", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 21, Country_IsoCode = "056", Country_CountryName = "Belgio", Country_Language = "ENG", Country_VIESCode = "BE", Country_CFiscCode = null },
            new Country() { Country_ID = 22, Country_IsoCode = "084", Country_CountryName = "Belize", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 23, Country_IsoCode = "204", Country_CountryName = "Benin", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 24, Country_IsoCode = "060", Country_CountryName = "Bermuda", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 25, Country_IsoCode = "064", Country_CountryName = "Bhutan", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 26, Country_IsoCode = "112", Country_CountryName = "Bielorussia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 27, Country_IsoCode = "068", Country_CountryName = "Bolivia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 28, Country_IsoCode = "070", Country_CountryName = "Bosnia Erzegovina", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 29, Country_IsoCode = "072", Country_CountryName = "Botswana", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 30, Country_IsoCode = "076", Country_CountryName = "Brasile", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 31, Country_IsoCode = "096", Country_CountryName = "Brunei", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 32, Country_IsoCode = "100", Country_CountryName = "Bulgaria", Country_Language = "ENG", Country_VIESCode = "BG", Country_CFiscCode = null },
            new Country() { Country_ID = 33, Country_IsoCode = "854", Country_CountryName = "Burkina Faso (Alto Volta)", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 34, Country_IsoCode = "108", Country_CountryName = "Burundi", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 35, Country_IsoCode = "120", Country_CountryName = "Camerun", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 36, Country_IsoCode = "124", Country_CountryName = "Canada", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 37, Country_IsoCode = "132", Country_CountryName = "Capo Verde", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 38, Country_IsoCode = "136", Country_CountryName = "Cayman", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 39, Country_IsoCode = "203", Country_CountryName = "Ceca Repubblica", Country_Language = "ENG", Country_VIESCode = "CZ", Country_CFiscCode = null },
            new Country() { Country_ID = 40, Country_IsoCode = "140", Country_CountryName = "Centrafricana Repubblica", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 41, Country_IsoCode = "148", Country_CountryName = "Ciad", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 42, Country_IsoCode = "152", Country_CountryName = "Cile", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 43, Country_IsoCode = "156", Country_CountryName = "Cina", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 44, Country_IsoCode = "196", Country_CountryName = "Cipro", Country_Language = "ENG", Country_VIESCode = "CY", Country_CFiscCode = null },
            new Country() { Country_ID = 45, Country_IsoCode = "170", Country_CountryName = "Colombia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 46, Country_IsoCode = "174", Country_CountryName = "Comore", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 47, Country_IsoCode = "180", Country_CountryName = "Congo Rep.Dem. (Zaire)", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 48, Country_IsoCode = "178", Country_CountryName = "Congo Repubblica", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 49, Country_IsoCode = "184", Country_CountryName = "Cook", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 50, Country_IsoCode = "408", Country_CountryName = "Corea del Nord", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 51, Country_IsoCode = "410", Country_CountryName = "Corea del Sud", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 52, Country_IsoCode = "384", Country_CountryName = "Costa d'Avorio", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 53, Country_IsoCode = "188", Country_CountryName = "Costa Rica", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 54, Country_IsoCode = "191", Country_CountryName = "Croazia", Country_Language = "ENG", Country_VIESCode = "HR", Country_CFiscCode = null },
            new Country() { Country_ID = 55, Country_IsoCode = "192", Country_CountryName = "Cuba", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 56, Country_IsoCode = "208", Country_CountryName = "Danimarca", Country_Language = "ENG", Country_VIESCode = "DK", Country_CFiscCode = null },
            new Country() { Country_ID = 57, Country_IsoCode = "212", Country_CountryName = "Dominica", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 58, Country_IsoCode = "214", Country_CountryName = "Dominicana Repubblica", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 59, Country_IsoCode = "218", Country_CountryName = "Ecuador", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 60, Country_IsoCode = "818", Country_CountryName = "Egitto", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 61, Country_IsoCode = "222", Country_CountryName = "El Salvador", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 62, Country_IsoCode = "784", Country_CountryName = "Emirati Arabi Uniti", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 63, Country_IsoCode = "232", Country_CountryName = "Eritrea", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 64, Country_IsoCode = "233", Country_CountryName = "Estonia", Country_Language = "ENG", Country_VIESCode = "EE", Country_CFiscCode = null },
            new Country() { Country_ID = 65, Country_IsoCode = "231", Country_CountryName = "Etiopia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 66, Country_IsoCode = "234", Country_CountryName = "Faeroer", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 67, Country_IsoCode = "238", Country_CountryName = "Falkland", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 68, Country_IsoCode = "242", Country_CountryName = "Figi", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 69, Country_IsoCode = "608", Country_CountryName = "Filippine", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 70, Country_IsoCode = "246", Country_CountryName = "Finlandia", Country_Language = "ENG", Country_VIESCode = "FI", Country_CFiscCode = null },
            new Country() { Country_ID = 71, Country_IsoCode = "250", Country_CountryName = "Francia", Country_Language = "ENG", Country_VIESCode = "FR", Country_CFiscCode = null },
            new Country() { Country_ID = 72, Country_IsoCode = "266", Country_CountryName = "Gabon", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 73, Country_IsoCode = "270", Country_CountryName = "Gambia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 74, Country_IsoCode = "268", Country_CountryName = "Georgia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 75, Country_IsoCode = "276", Country_CountryName = "Germania", Country_Language = "ENG", Country_VIESCode = "DE", Country_CFiscCode = null },
            new Country() { Country_ID = 76, Country_IsoCode = "288", Country_CountryName = "Ghana", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 77, Country_IsoCode = "388", Country_CountryName = "Giamaica", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 78, Country_IsoCode = "392", Country_CountryName = "Giappone", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 79, Country_IsoCode = "292", Country_CountryName = "Gibilterra", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 80, Country_IsoCode = "262", Country_CountryName = "Gibuti", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 81, Country_IsoCode = "400", Country_CountryName = "Giordania", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 82, Country_IsoCode = "300", Country_CountryName = "Grecia", Country_Language = "ENG", Country_VIESCode = "EL", Country_CFiscCode = null },
            new Country() { Country_ID = 83, Country_IsoCode = "308", Country_CountryName = "Grenada", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 84, Country_IsoCode = "304", Country_CountryName = "Groenlandia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 85, Country_IsoCode = "312", Country_CountryName = "Guadalupa", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 86, Country_IsoCode = "316", Country_CountryName = "Guam", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 87, Country_IsoCode = "320", Country_CountryName = "Guatemala", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 88, Country_IsoCode = "254", Country_CountryName = "Guayana Francese", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 89, Country_IsoCode = "624", Country_CountryName = "Guinea Bissau", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 90, Country_IsoCode = "226", Country_CountryName = "Guinea Equatoriale", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 91, Country_IsoCode = "324", Country_CountryName = "Guinea Repubblica", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 92, Country_IsoCode = "328", Country_CountryName = "Guyana", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 93, Country_IsoCode = "332", Country_CountryName = "Haiti", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 94, Country_IsoCode = "340", Country_CountryName = "Honduras", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 95, Country_IsoCode = "344", Country_CountryName = "Hong Kong", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 96, Country_IsoCode = "356", Country_CountryName = "India", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 97, Country_IsoCode = "360", Country_CountryName = "Indonesia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 98, Country_IsoCode = "364", Country_CountryName = "Iran", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 99, Country_IsoCode = "368", Country_CountryName = "Iraq", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 100, Country_IsoCode = "372", Country_CountryName = "Irlanda", Country_Language = "ENG", Country_VIESCode = "IE", Country_CFiscCode = null },
            new Country() { Country_ID = 101, Country_IsoCode = "352", Country_CountryName = "Islanda", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 102, Country_IsoCode = "376", Country_CountryName = "Israele", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 103, Country_IsoCode = "380", Country_CountryName = "Italia", Country_Language = "ITA", Country_VIESCode = "IT", Country_CFiscCode = null },
            new Country() { Country_ID = 104, Country_IsoCode = "891", Country_CountryName = "Jugoslavia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 105, Country_IsoCode = "116", Country_CountryName = "Kampuchea (Cambogia)", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 106, Country_IsoCode = "398", Country_CountryName = "Kazakistan", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 107, Country_IsoCode = "404", Country_CountryName = "Kenya", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 108, Country_IsoCode = "417", Country_CountryName = "Kirghizistan", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 109, Country_IsoCode = "296", Country_CountryName = "Kiribati", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 110, Country_IsoCode = "414", Country_CountryName = "Kuwait", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 111, Country_IsoCode = "418", Country_CountryName = "Laos", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 112, Country_IsoCode = "426", Country_CountryName = "Lesotho", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 113, Country_IsoCode = "428", Country_CountryName = "Lettonia", Country_Language = "ENG", Country_VIESCode = "LV", Country_CFiscCode = null },
            new Country() { Country_ID = 114, Country_IsoCode = "422", Country_CountryName = "Libano", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 115, Country_IsoCode = "430", Country_CountryName = "Liberia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 116, Country_IsoCode = "434", Country_CountryName = "Libia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 117, Country_IsoCode = "438", Country_CountryName = "Liechtenstein", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 118, Country_IsoCode = "440", Country_CountryName = "Lituania", Country_Language = "ENG", Country_VIESCode = "LT", Country_CFiscCode = null },
            new Country() { Country_ID = 119, Country_IsoCode = "442", Country_CountryName = "Lussemburgo", Country_Language = "ENG", Country_VIESCode = "LU", Country_CFiscCode = null },
            new Country() { Country_ID = 120, Country_IsoCode = "446", Country_CountryName = "Macao", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 121, Country_IsoCode = "807", Country_CountryName = "Macedonia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 122, Country_IsoCode = "450", Country_CountryName = "Madagascar", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 123, Country_IsoCode = "454", Country_CountryName = "Malawi", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 124, Country_IsoCode = "458", Country_CountryName = "Malaysia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 125, Country_IsoCode = "462", Country_CountryName = "Maldive", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 126, Country_IsoCode = "466", Country_CountryName = "Mali", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 127, Country_IsoCode = "470", Country_CountryName = "Malta", Country_Language = "ENG", Country_VIESCode = "MT", Country_CFiscCode = null },
            new Country() { Country_ID = 128, Country_IsoCode = "580", Country_CountryName = "Marianne", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 129, Country_IsoCode = "504", Country_CountryName = "Marocco", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 130, Country_IsoCode = "584", Country_CountryName = "Marshall", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 131, Country_IsoCode = "474", Country_CountryName = "Martinica", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 132, Country_IsoCode = "478", Country_CountryName = "Mauritania", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 133, Country_IsoCode = "480", Country_CountryName = "Mauritius", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 134, Country_IsoCode = "175", Country_CountryName = "Mayotte", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 135, Country_IsoCode = "484", Country_CountryName = "Messico", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 136, Country_IsoCode = "583", Country_CountryName = "Micronesia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 137, Country_IsoCode = "498", Country_CountryName = "Moldavia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 138, Country_IsoCode = "492", Country_CountryName = "Monaco Principato", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 139, Country_IsoCode = "496", Country_CountryName = "Mongolia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 140, Country_IsoCode = "500", Country_CountryName = "Monserrat", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 141, Country_IsoCode = "508", Country_CountryName = "Mozambico", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 142, Country_IsoCode = "104", Country_CountryName = "Myanmar (Birmania)", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 143, Country_IsoCode = "516", Country_CountryName = "Namibia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 144, Country_IsoCode = "520", Country_CountryName = "Nauru", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 145, Country_IsoCode = "524", Country_CountryName = "Nepal", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 146, Country_IsoCode = "558", Country_CountryName = "Nicaragua", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 147, Country_IsoCode = "562", Country_CountryName = "Niger", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 148, Country_IsoCode = "566", Country_CountryName = "Nigeria", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 149, Country_IsoCode = "570", Country_CountryName = "Niue", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 150, Country_IsoCode = "999", Country_CountryName = "Non Classificabile", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 151, Country_IsoCode = "574", Country_CountryName = "Norfolk", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 152, Country_IsoCode = "578", Country_CountryName = "Norvegia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 153, Country_IsoCode = "540", Country_CountryName = "Nuova Caledonia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 154, Country_IsoCode = "554", Country_CountryName = "Nuova Zelanda", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 155, Country_IsoCode = "528", Country_CountryName = "Olanda (Paesi Bassi)", Country_Language = "ENG", Country_VIESCode = "NL", Country_CFiscCode = null },
            new Country() { Country_ID = 156, Country_IsoCode = "512", Country_CountryName = "Oman", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 157, Country_IsoCode = "586", Country_CountryName = "Pakistan", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 158, Country_IsoCode = "585", Country_CountryName = "Palau", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 159, Country_IsoCode = "591", Country_CountryName = "Panama", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 160, Country_IsoCode = "598", Country_CountryName = "Papua Nuova Guinea", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 161, Country_IsoCode = "600", Country_CountryName = "Paraguay", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 162, Country_IsoCode = "604", Country_CountryName = "Perù", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 163, Country_IsoCode = "258", Country_CountryName = "Polinesia Francese", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 164, Country_IsoCode = "616", Country_CountryName = "Polonia", Country_Language = "ENG", Country_VIESCode = "PL", Country_CFiscCode = null },
            new Country() { Country_ID = 165, Country_IsoCode = "620", Country_CountryName = "Portogallo", Country_Language = "ENG", Country_VIESCode = "PT", Country_CFiscCode = null },
            new Country() { Country_ID = 166, Country_IsoCode = "630", Country_CountryName = "Portorico", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 167, Country_IsoCode = "634", Country_CountryName = "Qatar", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 168, Country_IsoCode = "826", Country_CountryName = "Regno Unito", Country_Language = "ENG", Country_VIESCode = "GB", Country_CFiscCode = null },
            new Country() { Country_ID = 169, Country_IsoCode = "638", Country_CountryName = "Reunione", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 170, Country_IsoCode = "642", Country_CountryName = "Romania", Country_Language = "ENG", Country_VIESCode = "RO", Country_CFiscCode = null },
            new Country() { Country_ID = 171, Country_IsoCode = "646", Country_CountryName = "Ruanda", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 172, Country_IsoCode = "643", Country_CountryName = "Russia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 173, Country_IsoCode = "659", Country_CountryName = "Saint Kittis e Nevis", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 174, Country_IsoCode = "662", Country_CountryName = "Saint Lucia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 175, Country_IsoCode = "666", Country_CountryName = "Saint Pierre e Miquelon", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 176, Country_IsoCode = "670", Country_CountryName = "Saint Vincent e Grenadine", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 177, Country_IsoCode = "090", Country_CountryName = "Salomone", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 178, Country_IsoCode = "882", Country_CountryName = "Samoa", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 179, Country_IsoCode = "016", Country_CountryName = "Samoa Americane", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 180, Country_IsoCode = "674", Country_CountryName = "San Marino", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 181, Country_IsoCode = "678", Country_CountryName = "Sao Tomè e Principe", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 182, Country_IsoCode = "686", Country_CountryName = "Senegal", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 183, Country_IsoCode = "690", Country_CountryName = "Seychelles", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 184, Country_IsoCode = "694", Country_CountryName = "Sierra Leone", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 185, Country_IsoCode = "702", Country_CountryName = "Singapore", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 186, Country_IsoCode = "760", Country_CountryName = "Siria", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 187, Country_IsoCode = "703", Country_CountryName = "Slovacca Repubblica", Country_Language = "ENG", Country_VIESCode = "SK", Country_CFiscCode = null },
            new Country() { Country_ID = 188, Country_IsoCode = "705", Country_CountryName = "Slovenia", Country_Language = "ENG", Country_VIESCode = "SI", Country_CFiscCode = null },
            new Country() { Country_ID = 189, Country_IsoCode = "706", Country_CountryName = "Somalia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 190, Country_IsoCode = "724", Country_CountryName = "Spagna", Country_Language = "ENG", Country_VIESCode = "ES", Country_CFiscCode = null },
            new Country() { Country_ID = 191, Country_IsoCode = "144", Country_CountryName = "Sri Lanka", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 192, Country_IsoCode = "840", Country_CountryName = "Stati Uniti d'America", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 193, Country_IsoCode = "710", Country_CountryName = "Sudafricana Repubblica", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 194, Country_IsoCode = "736", Country_CountryName = "Sudan", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 195, Country_IsoCode = "740", Country_CountryName = "Suriname", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 196, Country_IsoCode = "752", Country_CountryName = "Svezia", Country_Language = "ENG", Country_VIESCode = "SE", Country_CFiscCode = null },
            new Country() { Country_ID = 197, Country_IsoCode = "756", Country_CountryName = "Svizzera", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 198, Country_IsoCode = "748", Country_CountryName = "Swaziland", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 199, Country_IsoCode = "762", Country_CountryName = "Tagikistan", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 200, Country_IsoCode = "158", Country_CountryName = "Taiwan", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 201, Country_IsoCode = "834", Country_CountryName = "Tanzania", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 202, Country_IsoCode = "764", Country_CountryName = "Thailandia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 203, Country_IsoCode = "768", Country_CountryName = "Togo", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 204, Country_IsoCode = "776", Country_CountryName = "Tonga", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 205, Country_IsoCode = "780", Country_CountryName = "Trinidad e Tobago", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 206, Country_IsoCode = "788", Country_CountryName = "Tunisia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 207, Country_IsoCode = "792", Country_CountryName = "Turchia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 208, Country_IsoCode = "795", Country_CountryName = "Turkmenistan", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 209, Country_IsoCode = "796", Country_CountryName = "Turks e Caicos", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 210, Country_IsoCode = "798", Country_CountryName = "Tuvalu", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 211, Country_IsoCode = "804", Country_CountryName = "Ucraina", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 212, Country_IsoCode = "800", Country_CountryName = "Uganda", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 213, Country_IsoCode = "348", Country_CountryName = "Ungheria", Country_Language = "ENG", Country_VIESCode = "HU", Country_CFiscCode = null },
            new Country() { Country_ID = 214, Country_IsoCode = "858", Country_CountryName = "Uruguay", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 215, Country_IsoCode = "860", Country_CountryName = "Uzbekistan", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 216, Country_IsoCode = "548", Country_CountryName = "Vanuatu", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 217, Country_IsoCode = "336", Country_CountryName = "Vaticano", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 218, Country_IsoCode = "862", Country_CountryName = "Venezuela", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 219, Country_IsoCode = "850", Country_CountryName = "Vergini Is. Americane", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 220, Country_IsoCode = "092", Country_CountryName = "Vergini Is. Britanniche", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 221, Country_IsoCode = "704", Country_CountryName = "Vietnam", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 222, Country_IsoCode = "581", Country_CountryName = "Wake", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 223, Country_IsoCode = "876", Country_CountryName = "Wallis e Futuna", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 224, Country_IsoCode = "887", Country_CountryName = "Yemen", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 225, Country_IsoCode = "894", Country_CountryName = "Zambia", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null },
            new Country() { Country_ID = 226, Country_IsoCode = "716", Country_CountryName = "Zimbabwe", Country_Language = "ENG", Country_VIESCode = null, Country_CFiscCode = null }
        };
    }
}
