// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eGym.Core.Localization;

namespace eGym.Core.Localization.Migrations
{
    [DbContext(typeof(LocalizationDbContext))]
    partial class LocalizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("eGym.Core.Localization.CMS_History", b =>
                {
                    b.Property<int>("CMSH_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("CMSH_Active")
                        .HasColumnType("bit");

                    b.Property<string>("CMSH_Culture")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("CMSH_MasterID")
                        .HasColumnType("int");

                    b.Property<string>("CMSH_Value")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.HasKey("CMSH_ID");

                    b.HasIndex("CMSH_MasterID");

                    b.ToTable("CMS_History");
                });

            modelBuilder.Entity("eGym.Core.Localization.CMS_Master", b =>
                {
                    b.Property<int>("CMS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("CMS_Active")
                        .HasColumnType("bit");

                    b.Property<string>("CMS_ContextKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CMS_Culture")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<short>("CMS_EditorTypeID")
                        .HasColumnType("smallint");

                    b.Property<string>("CMS_GroupKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CMS_Value")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.HasKey("CMS_ID");

                    b.ToTable("CMS_Master");
                });

            modelBuilder.Entity("eGym.Core.Localization.CMS_History", b =>
                {
                    b.HasOne("eGym.Core.Localization.CMS_Master", "CMS_Master")
                        .WithMany("CMS_Histories")
                        .HasForeignKey("CMSH_MasterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CMS_Master");
                });

            modelBuilder.Entity("eGym.Core.Localization.CMS_Master", b =>
                {
                    b.Navigation("CMS_Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
